// Mock data for frontend development before Manny's loader is ready
// All values from verified numbers in CLAUDE.md and DESIGN.md — no invented stats
// Includes: Green River clusters (King, Pierce, Spokane, Snohomish, Clark), DC cluster

import type { Cluster, Case, ReliabilityBadge } from "@/lib/types";
import { getConfidenceLevel } from "@/lib/constants";

// ── Mock Clusters ──
// Green River demo: WA + Female + Strangulation + 1980–2000
// DESIGN.md verified: 128 total cases, ~48% unsolved

export const MOCK_CLUSTERS: Cluster[] = [
  {
    id: "wa-king",
    name: "King County, WA",
    county_fips: "53033",
    state: "Washington",
    total_cases: 52,
    unsolved_cases: 25,
    solve_rate: 0.519,
    lat: 47.6062,
    lng: -122.3321,
    year_start: 1980,
    year_end: 2000,
    jurisdictions: 4,
  },
  {
    id: "wa-pierce",
    name: "Pierce County, WA",
    county_fips: "53053",
    state: "Washington",
    total_cases: 18,
    unsolved_cases: 9,
    solve_rate: 0.5,
    lat: 47.2529,
    lng: -122.4443,
    year_start: 1982,
    year_end: 1998,
    jurisdictions: 3,
  },
  {
    id: "wa-spokane",
    name: "Spokane County, WA",
    county_fips: "53063",
    state: "Washington",
    total_cases: 14,
    unsolved_cases: 7,
    solve_rate: 0.5,
    lat: 47.6588,
    lng: -117.426,
    year_start: 1983,
    year_end: 1999,
    jurisdictions: 2,
  },
  {
    id: "wa-snohomish",
    name: "Snohomish County, WA",
    county_fips: "53061",
    state: "Washington",
    total_cases: 8,
    unsolved_cases: 4,
    solve_rate: 0.5,
    lat: 47.979,
    lng: -122.2021,
    year_start: 1985,
    year_end: 1997,
    jurisdictions: 2,
  },
  {
    id: "wa-clark",
    name: "Clark County, WA",
    county_fips: "53011",
    state: "Washington",
    total_cases: 7,
    unsolved_cases: 3,
    solve_rate: 0.571,
    lat: 45.6387,
    lng: -122.6615,
    year_start: 1986,
    year_end: 1995,
    jurisdictions: 2,
  },
  {
    id: "dc-district",
    name: "District of Columbia",
    county_fips: "11001",
    state: "District of Columbia",
    total_cases: 7108,
    unsolved_cases: 4677,
    solve_rate: 0.342,
    lat: 38.9072,
    lng: -77.0369,
    year_start: 1976,
    year_end: 2023,
    jurisdictions: 1,
  },
];

// ── Mock Cases (sample rows for MiniCaseTable in Case File page) ──
export const MOCK_CASES: Case[] = [
  {
    id: "case-001",
    ori: "WA0170100",
    agency: "Seattle Police Department",
    agency_type: "Municipal",
    state: "Washington",
    year: 1984,
    month: 7,
    solved: false,
    victim_sex: "Female",
    victim_age: 26,
    victim_race: "White",
    victim_ethnicity: "Not Hispanic",
    offender_sex: "Unknown",
    offender_age: 0,
    offender_race: "Unknown",
    offender_ethnicity: "Unknown",
    weapon_code: 80,
    weapon_label: "Strangulation",
    relationship: "Unknown",
    county_fips: "53033",
    msa: "Seattle-Tacoma-Bellevue",
    circumstance: "Unknown",
    lat: 47.6062,
    lng: -122.3321,
  },
  {
    id: "case-002",
    ori: "WA0170100",
    agency: "Seattle Police Department",
    agency_type: "Municipal",
    state: "Washington",
    year: 1985,
    month: 3,
    solved: true,
    victim_sex: "Female",
    victim_age: 31,
    victim_race: "Black",
    victim_ethnicity: "Not Hispanic",
    offender_sex: "Male",
    offender_age: 34,
    offender_race: "White",
    offender_ethnicity: "Not Hispanic",
    weapon_code: 80,
    weapon_label: "Strangulation",
    relationship: "Stranger",
    county_fips: "53033",
    msa: "Seattle-Tacoma-Bellevue",
    circumstance: "Other",
    lat: 47.6062,
    lng: -122.3321,
  },
  {
    id: "case-003",
    ori: "WA0170200",
    agency: "King County Sheriff",
    agency_type: "County",
    state: "Washington",
    year: 1986,
    month: 11,
    solved: false,
    victim_sex: "Female",
    victim_age: 22,
    victim_race: "White",
    victim_ethnicity: "Not Hispanic",
    offender_sex: "Unknown",
    offender_age: 0,
    offender_race: "Unknown",
    offender_ethnicity: "Unknown",
    weapon_code: 80,
    weapon_label: "Strangulation",
    relationship: "Unknown",
    county_fips: "53033",
    msa: "Seattle-Tacoma-Bellevue",
    circumstance: "Unknown",
    lat: 47.5501,
    lng: -122.2729,
  },
];

// ── Mock State Reliability (from State_Reporting_Rates_2022.xlsx) ──
export const MOCK_STATE_RELIABILITY: ReliabilityBadge[] = [
  {
    state: "Mississippi",
    agencies_total: 300,
    agencies_reporting: 72,
    reporting_pct: 24,
    confidence: getConfidenceLevel(24),
  },
  {
    state: "Florida",
    agencies_total: 400,
    agencies_reporting: 192,
    reporting_pct: 48,
    confidence: getConfidenceLevel(48),
  },
  {
    state: "Iowa",
    agencies_total: 225,
    agencies_reporting: 133,
    reporting_pct: 59,
    confidence: getConfidenceLevel(59),
  },
  {
    state: "Washington",
    agencies_total: 260,
    agencies_reporting: 239,
    reporting_pct: 92,
    confidence: getConfidenceLevel(92),
  },
];
